package subastas;

/**
 *
 * @author lpsotoHP
 */
public enum TipoMensaje {
    LOGIN, LOGOUT, SUCCESSLOGIN, GETMENU, ORDER, REGISTRARAGENTE, UNKNOWN, OK
    , CONSULTARPROPIEDAD, LOGINAGENTE, LOGINADMIN, LOGINCLIENTE, TERMINATESERVER,
    UNKNOW, USUARIOCONTRASENAERRONEA, USUARIONOEXISTE, CONSULTACLIENTE, CONSULTAAGENTE
    , REGISTRARLOTE, REGISTRARCASA, REGISTRARCENTROCOMERCIAL, REGISTRARAPARTAMENTO, MOSTRARINTERES
    , VERCATALOGO, VERINTERESADOS, ELIMINARPROPIEDAD, ORDENARPROPIEDADES, VERPROPIEDADES, AGREGARCOMENTARIO,
    MODIFICARPROPIEDAD
}