package subastas;

/**
 *
 * @author lpsotoHP
 */
public enum TipoMensaje {
    UNKNOWN,INICIARSUBASTA, CONSULTASUBASTA, OFERTA, RECHAZAROFERTA, ACEPTAROFERTA, 
    UNIRSESUBASTA, SUBASTACANCELADA,SUBASTAFINALIZADA,
}