package redsocial.model;

/**
 *
 * @author lpsotoHP
 */
public enum TipoMensaje {
    UNKNOWN, SEGUIRVIP, DEJARSEGUIRVIP, LIKEMENSAJE, DISLIKEMENSAJE, DARSEBAJA, 
    POSTEARMENSAJE, NOTIFICACIONNIVEL, NOTIFICACIONMENSAJE
} 