package javabomboclat;

/**
 *
 * @author lpsotoHP
 */
public enum MessageType {
    AGREGAROBSERVABLE, AGREGAROBSERVADOR, CERRARCONEXION, QUITAROBSERVABLE,LOGIN,
    NOTIFICAROBSERVABLE,NOTIFICAROBSERVADORES, UNKNOWN
} 