package subastas;

/**
 *
 * @author lpsotoHP
 */
public enum TipoMensaje {
    UNKNOWN, OFERTA, RECHAZAROFERTA, ACEPTAROFERTA, UNIRSESUBASTA, SUBASTACANCELADA, 
    SUBASTAFINALIZADA, INICIARSUBASTA, CONSULTASUBASTA
}